apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster-producer-tests
  namespace: kafka-mwt
status:
  readyReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster-consumer-tests
  namespace: kafka-mwt
status:
  readyReplicas: 1
